version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: gerenciar-times-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gerenciar_times
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - gerenciar-times-network

networks:
  gerenciar-times-network:
