spring:
  application:
   name: gerenciar-times
  output:
    ansi:
      enabled: ALWAYS
  datasource:
   url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/gerenciar_times?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
   username: ${DATASOURCE_USERNAME:admin}
   password: ${DATASOURCE_PASSWORD:admin}
   driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   show-sql: true
   hibernate:
    ddl-auto: none
   properties:
    hibernate.format_sql: true

logging:
 pattern:
  console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
 file:
  name: app.log
 level:
  org:
   hibernate:
    type: trace
